### ISSUE TITLE
Any suggestions for understanding the ISL code in Tiramisu?

### ISSUE THREAD

**Issue by Superjomn** [Tiramisu-Compiler/tiramisu#279]
Hello Tiramisu developers:

I am a software developer interested in the Tiramisu project.

Currently, I'm reading the Tiramisu codes and find complex usage of ISL for the polyhedral analysis.

I wonder how you developers can master the ISL so fluently, as far as I googled through the Internet and just found several documents about the ISL, with very few demos and examples about the API.

- [ISL manual](http://isl.gforge.inria.fr/manual.pdf)
- [Presburger Formulas and Polyhedral Compilation](https://www.researchgate.net/profile/Sven_Verdoolaege/publication/291352331_Presburger_Formulas_and_Polyhedral_Compilation/links/56a21c2008ae27f7de29ae1d/Presburger-Formulas-and-Polyhedral-Compilation.pdf)

After reading these documentations, I found it still hard to understand the ISL usage code in the Tiramisu project.

Can you provide some suggestions about the materials for mastering the ISL APIs?

**Comment by rbaghdadi** [comment]
Hi Yan,

Can you please post this question on the tiramisu mailing list? ISL
developers on that list will help you much better.

tiramisu@lists.csail.mit.edu

There is a link to subscribe in the Tiramisu mailing list, you can find it
in the Tiramisu website.

Many thanks,

**Comment by rbaghdadi** [comment]
I just forwarded your question to the Tiramisu mailing list. Please let me know if you didn't get a copy of it.

**Comment by Superjomn** [comment]
Many thanks for your suggestion!

I've got the copy, and I will look deeper into it.

Awesome code by the way : )

**Comment by rbaghdadi** [comment]
Thanks Yan! If you are interested in helping please let us know. Contributions are very welcome :) !

**Comment by 4fterlook** [comment]
Hello Riyadh! I have same questions as Yan did and I subscribed Tiramisu’s mailing list to check if anyone had answered this question, yet I cannot find this discussion in mailing list archive. Is it a mailing system problem or my own mistake, could you help me with that? Thank you very much!

**Comment by rbaghdadi** [comment]
Hi @4fterlook , 

If you want to learn ISL, I suggest reading the following:

- All the polyhedral operations in Tiramisu (http://tiramisu-compiler.org/) and in other state-of-the-art compilers use the ISL library (ISL stands for integer set library): http://isl.gforge.inria.fr/ 
It is a library for representing sets of integer tuples, maps (or relations) between sets of integer tuples and operations on the sets and maps. Chapter 1.2 in the documentation of the barvinok tool (which is built on top of ISL), is a good introduction for what are sets, maps, … http://barvinok.gforge.inria.fr/barvinok.pdf
Instead of using barvinok, I suggest the use of ISLPy which is the Python interface of ISL: https://documen.tician.de/islpy/ 

- The polyhedral model tutorial: http://polycomp.gforge.inria.fr/ 

- The following website has good pointers about papers in the area of polyhedral compilation: http://polyhedral.info/

**Comment by 4fterlook** [comment]
Thank you Riyadh! This really helps me a lot.
